name: flake8

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  flake8:

    runs-on: ubuntu-latest # denotes what operating system the job is going to run on

    steps:
    - uses: actions/checkout@v2 # git clones the repo onto the virtual machine

    - name: Set up Python 3.10 # creates the environment in Python version
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies # runs these individual commands in the new environment
      run: |
        pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 .
